name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2

    - name: Copy .env
      working-directory: ./project 
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      working-directory: ./project 
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      working-directory: ./project 
      run: php artisan key:generate

    - name: Directory Permissions
      working-directory: ./project 
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      working-directory: ./project 
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ./project 
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
